<div class="row border-head article">
    <p>THE PASSION OF THE PATH OF ACHRA</p>
    <p>BY DAHLIA MEAT</p>
    <p></p>
    <p>i have set a timer for 90 minutes. here goes !!!</p>
    <p>i have 90 minutes to review path of achra - or, at least, to write this script and upload it. afterward, i may edit it and modify it, but my website has been empty for months upon months and i have yet to receive a diagnosis for ocd because i have spent three months figuring out health insurance because i turned 26 and i needed healtcare asap because adhd, and stimulants do wonders for me to the degree that i havent sought out therapy or any other medication because at least i can work and do all the chores and do all the errands and once i begin the work and the chores and the errands i realize i have no time to do anything else because i spent all my time not doing the work and chores and errands before finally doing the work and chores and errands and my website is empty and i'm attending school 45 miles away from my home because i have one semester left receiving a certain grant before receiving my AA but i haven't gotten the grant for the semester yet and finals are this week and im talking 72 hours from now and im attending school 45 miles away because i moved 55 miles away with one semester left on my AA and they campus is in the same district.</p>
    <p>i interviewed path of achra developer "ulfsire" over five months ago at 10:00 AM PT, sweating buckets in the july heat of a second-story uncooled sunroom as to minimize noise, minutes before driving 40 miles from someone's home that is not my own. i was so scrambled that i fucked up the last moment of my interview. i was writing my parting words while he was giving the most sincere and raw answer of the entire interview. i hardly caught what he said. this was bad active listening, but i was multitasking. i set a deadline for myself for the interview so i could just get it out and not worry about it being fucking perfect. it doesn't need to be perfect. </p>
    <p>"Thank you so much for your time! I'm quite happy with how it went. I'll send you the review once it's published," i say. i wanted the review to be out within only a few months of the game's release. the year is almost over. too much on my plate. i need a degree. priorities. priorities. obligations. not falling apart. job. work. school. art? no time today. maybe an hour of noita. maybe an hour with the girlfriend. maybe a day of rest. maybe an all-nighter studying calculus. the review was not made.</p>
    <p>the story of ulfsire and his debut commercial game is as engaging as his debut game is to play. the game was developed, as far as my research is aware, entirely solo. numerous times, ulfsire has stated he developed this game in godot after years of wanting to make games. ulfsire is a lover of a select few "classic roguelikes" (or, as i say: "true roguelikes"), as just about any fan of "classic/true roguelikes" can only sink so many hours into so many "true roguelikes" (becoming good enough at the games to love them). his favourites, he told me (though i already knew, in meticulously researching him for two months prior to the interview), included tales of maj'eyal (TOME) and dungeon crawl stone soup, two games i have yet to even play (well i played DCSS for likeee 20 minutes in a library three days before interviewing ulfsire). can't make the review until i understand those games. cant understand those games until i play for at least 40 hours each.</p>
    <p>just make it. just start making it. stop thinking about making it and just start making it, right now. stop what you are doing and start making it. START MAKING IT. START MAKING IT, WHATEVER IT IS, MAKE IT. MAKE SOMETHING CLOSE TO IT. MAKE SOMETHING AKIN TO IT IN ONE PERCENT THE AMOUNT OF TIME YOU KNOW YOU WOULD NEED TO SPEND ON IT TO MAKE IT "PERFECT". DRAW A SQUARE. NOW MAKE IT CLOSER TO PERFECT. NOW MAKE IT CLOSER TO PERFECT. HOW LONG BEFORE YOU ARE SATISFIED? WHO ARE YOU SATISFYING?</p>
    <p>path of achra is the path of archa of the path of achra. you know?</p>
    <p>your first run of path of achra will feel like returning to school for the first time in five years. all of the nightmares about arriving to school after years of not attending will mostly disappear. you know? the dreams where you show up to a campus you feel as though you once had some architecture navigational understanding of, but it's been demolished and rebuilt based on the valedictorian's memory of the entire campus layout each year since you graduated with a 3.1 GPA. reality is not like those dreams, but you are accustomed to feeling out of your depth all the same. it hurts. sometimes it makes you feel as though you could have tricked yourself and everyone in the world into believing that you are an adult, because you feel like a child, and you don't understand, and everything is so scary, and there's too much information, and you want to go home so badly you begin to feel sick. you go to the nurse and call path of achra. path of achra picks you up from school driving the bus from Speed (1994) and takes you home, and path of achra doesn't yell at you, but you yell at yourself inside your own head, and you will do this for the rest of your life, and you will stop doing this when and if you ever decide to lower your voice.</p>
    <p>your first run of path of achra will feel like returning to school for the first time in five years with a new major in computer science. you want to make games? you need to take calculus. remember? that field of mathematics that behooved you to stop saying "math is my favourite subject" in high school? your professor says you should be familiar with trigonometry. you, actually, for serious, gun to your head, could not define what trigonometry is. </p>
    <p>path of achra is your professor, after class, asking if you remember the unit circle. you say no. she shows you the unit circle. holy shit, look at that thing. how much of this do i need to memorize? all of it, actually. you want to cry. during your first exam in this class, you do cry, and you cry so hard and so quietly that you fill your black cloth mask with snot and there are no sinks in any of the bathrooms on the first floor of the building after you finish the 1/3 of the exam before time runs out and you are given a 15 minute break before lecture resumes because "we're actually behind on lecture." you want to go home. you consider asking the nurse to call path of achra. you don't ask path of achra to pick you up from college, because you're 25 and path of achra lives in a different city now, but path of achra is still paying your phone bill.</p>
    <p>you scored a 33.75% on that exam. 60% of the exam you left blank. path of achra is also that exam. path of achra is also the take-home second exam you scored a 98.44% on. path of achra is the third exam you scored a 96.25% on. path of achra is knowing that each of these three exams was 15% of your grade. path of achra is knowing that the final is worth 40% of your grade. path of achra is knowing that if you score a 90% on the final exam, the same score will be be given to your worst exam grade.</p>
    <p>path of achra is getting a 91.76% on your final fucking exam and getting up from your desk doing a fucking hospital flip in class and chugging the liter of lactaid jacob brought to the exam and the last five lectures because he says he's trying to bulk up.</p>
    <p>path of achra is the unit circle and i memorized it. 0 degrees 0 radians (1, 0),  30 degrees pi/6 radians (sqrt(3)/2, 1/2), 45 deg pi/4 rad (sqrt(2)/2, sqrt(2)/2), 60 deg pi/3 rad (1/2, sqrt(3)/2), 90 d pi/2 r (0, 1), thats one quadrant of four, degrees increase by this same pattern, take the same coordinates and mirror them across each axis and make negative what should be negative according to quadrant, radians are a little tricky but easy to grasp if you notice that pi/3 is just 2pi/6 which means the top and bottom half of the circle are divided into 6 pieces from 0 to pi and pi/4 is just doing the same but into four pieces. that's a little confusing but if you notice the xpi/6 -> xpi/4 -> xpi/3 -> xpi/2 -> xpi/3 -> xpi/4 -> xpi/6 pattern you'll notice in the first quadrant that x = 1 and in the second quadrant x = one less than the denominator, third quadrant x = one more than the denominator, fourth quadrant x = 1 less than double the denominator.</p>
    <p>something that once daunted me, something that made me feel stupid and out of my depth, something that made me feel like a clueless child makes such perfect sense to me sixth months later that i can draw it from memory because i understand exactly what it is. path of achra is the unit circle and i understand it. i haven't played path of achra in over four months and imagining playing path of achra right now feels almost as good as playing path of achra because i understand it.</p>
    <p>path of achra is a testament to the virtues of patience and studying the manual of a machine you will be tested on your ability to interface with. path of achra is also bumping a line of adderall off a d&d 2e character sheet and sprinting past the Costco entrance workers with a scimitar in real life and screaming when they chase you. path of achra's utmost faith in all its careful ideas are bike-to-daiso-summer-day-chug-cold-pocari-sweat-levels refreshing, and it also, sometimes, plays like if cookie clicker was a guillotine-heavy and guillotine-sharp CYOA novel that will decapitate you if it falls off the shelf, and your dog starts barking like an earthquake is coming</p>
    <p>the goal of path of achra is to dream a guy so fucked up that he kills everyone he passes on the sidewalk while walking to his job at the magnetic car factory that makes ten thousand different kinds of cars that all magnetically attract only opossums, raccoons, squirrels, and other small animals.</p>
    <p>WHAT ARE YOU TALKING ABOUT AND WHY ARE YOU SAYING IT LIKE THIS HOLY SHIT WHAT IS PATH OF ACHRA?</p>
    <p>path of achra is a labour of love from a person that believed in themselves and continues to believe in themselves. path of achra is a full, real, good, smart, satisfying, savoury, rube-goldbergian digital k-hole hypnotist of a video game made by a person who had previously only made custom game modes in warcraft 3.</p>
    <p>to those unfamiliar with roguelikes, path of achra may resemble dwarf fortress. to roguelike likers, path of achra may resemble a "classic roguelike". to roguelike gourmands, path of achra is a rift-wizard-like. this is how ulfsire describes his game.</p>
    <p>"it's more of a rift-wizard-like than a roguelike."</p>
    <p>to those familiar with rift wizard: fuck yeaaah, fucking rift wizardddd, duuude, </p>
    <p>to those familiar with rift wizard and unfamiliar with path of achra: firstly, i made you up, and secondly, path of achra is like rift wizard autochess in a world where autochess is actually as interesting and complex as the phrase "autochess" sounds</p>
    <p>to those unfamiliar with rift wizard and familiar with noita and slay the spire: path of achra is like turn-based noita without the wand mechanics or the open world with slay the spire mechanics except take out the cards and relics. i haven't slept in 48 hours and this paragraph was written 90% earnestly</p>
    <p>to those who don't find this funny and also to everyone else because i have thirty minutes left and somebody is probably waiting for me to talk about the game: hey, don't want for me to do anything unless i say i'm gonna do it later. if you want to know about the game, BUY IT, and patiently, curiously play it. it's $9.99 and ulfsire deserves your support for believing in himself enough to eschew the comfort of not spending his times home from work turning his brain off and relaxing with his favourite games, choosing to commit to two years of tireless effort creating his new favourite game; a passionate, endearing, inspiring, watertight game that poses, humble yet proud, for a group photo. surrounding path of achra in the photo are multiple games that inspired it.</p>
    <p>16 minutes left. to speak directly, path of achra is similar to many roguelikes in that synergies are the name of the game. status effects and buffs and damage types are colour-coded and can be typed into a search bar. this does not mean path of achra is so dense it is unapproachable. path of achra is intimidating for the first hour or so. path of achra clicks quite fast.</p>
    <p>the structure of path of achra's gameplay loop is brilliant. there are no slow starts to runs. rooms can be cleared in seconds. all 90 skills are available to spec into from the first frame of gameplay. path of achra gives you 10 skill points to start. usually, it gives you another just for the road. sometimes it gives you two. i don't know why path of achra does this. i love it.</p>
    <p>items in path of achra are brilliant. they are fixed items. fuck borderlands! im sorry, fuck borderlands. borderlands is an entry-fee all-you-can-eat fps gacha reddit buffet. i don't want to wait for a cool randomized gun to appear. i want to look all three upcoming areas i can choose to travel to and see exactly what enemies will be there, how they work, and what loot i will gain upon clearing that area. that item has a name. every item in path of achra has a name. that item will always behave exactly like that item. the items are rewarded to the player all at once on the last screen of the area they traveled to. pressing tab throughout screens of combat enable an incredibly simply, non-intelligent "automated action" button that will either approach/attack the nearest enemy or pick up the remaining loot. loot may be sacrificed to increase the stats of the loot you are holding. there are (and i calculated this with a mathematics nerd i met on grindr) literally hundreds of sextillions of possible builds in this game, and it's not the slightest bit daunting. there are about four different screens you access during a run to create or level or arm your character, and these four screens alone allow for so many permutations of play that path of achra stops becoming a game about winning and starts becoming a game about learning and relaxing. at points, you may find yourself in such a near-death run that you feel the rhythm of your heart change, or the position of your stomach slide. path of achra is, sometimes, dangerous. i haven't played path of achra in over four months and imagining playing path of achra right now feels almost as good as playing path of achra. time's up!</p>
    <p>i could gush about path of achra for another 90 minutes right now if i truly wanted to. i wrote all of this in 1.5 hours. i can go for another 90 solely because i decided i would only give myself 90 and that made me actually start, and that's enough sometimes. i interviewed the developer of path of achra 3,766 hours ago. 157 days of putting off this review, and why? it felt terrible to keep thinking about how this review was no closer to being made. it was agonizing to think about my empty website. it is painful to release such a ridiculous "review", but finishing anything is painful. it is painful to finish something you're proud, and it is painful to finish something you're not proud of. </p>
    <p>ulfsire worked hard on path of achra and i've worked hard on my new degree. work is always some angle of exhausting, some flavour of tedium. </p>
    <p>THERE ARE ONLY SO MANY HOURS AND YOU MAY DIVIDE YOUR HOURS INTO AS MANY PROJECTS AS YOU WISH</p>
    <p>TRY FINISHING ONE PROJECT TODAY </p>
    <p>NO MATTER HOW SHIT IT IS</p>
    <p>YOU KNOW YOU HAVE TO PRACTICE, DON'T YOU? WE ALL KNOW THAT, YEAH?</p>
    <p>WHY ARE YOU ONLY PRACTICING THE "STARTING PROJECTS" PART?</p>
    <p>WHY NOT FINISH SOMETHING FOR THE SAKE OF PRACTICING THE "FINISHING A PROJECT" PART?</p>
    <p>IT WILL ALWAYS FEEL BETTER TO FINISH SOMETHING MESSY THAN TO START SOMETHING PROMISING AND NEVER FINISH IT</p>
    <p>START SOMETHING WITH THE KNOWLEDGE YOU HAVE ONLY A COUPLE HOURS TO MAKE IT AND THEN FINISH IT</p>
    <p>I PROMISE YOU IT FEELS SO GOOD</p>
    <p>I FEEL SO GOOOOOOD</p>
    <p>PATH OF ACHRA IS SOOO GOOD DUUDE, LIKEEE</p>
</div>