<svelte:head>
	<title>RULES FOR PORNSICK DOVAHKIIN</title>
    <meta name="RULES FOR PORNSICK DOVAHKIIN by tess" content="a guide" />
    <meta property="og:title" content="RULES FOR PORNSICK DOVAHKIIN">
    <meta property="og:description" content="Do not reflect on your actions for even one second until you are done.">
    <meta property="og:image" content="https://null.skin/images/essay-images/rules-for-pornsick-dovahkiin/rfpsdnull.png">
</svelte:head>
<div class="row border-head">
    <div class="article article-body">
        <p></p>
        <h1 style="margin: 0; padding-top:0.75rem;">RULES FOR PORNSICK DOVAHKIIN</h1>   
        <h3 style="margin-top: -0.2em;"><i>a guide</i></h3>
        <div class="row author">
			<a class="nav-item nav-link variable-manrope" href="/creators/tess">
				by tess
			</a>
		</div>
        <div class="row article-date">
            March 30, 2025
        </div>
        <br>
        <img class="article-screenshot" src="/images/essay-images/rules-for-pornsick-dovahkiin/nullrfpsd2.png" alt="porn-modded skyrim screenshot">
        <h3>DO THE PREREQUISITES FIRST.</h3>
        <p>Make sure your mod loader is updated. Install the Skyrim Script Extender, SkyUI, the Mod Configuration Menu, the Unofficial Elder Scrolls Patch, performance fixes, tweaks, improvements. Make sure you’ve got mods that prevent crashes, too. What you’re about to do will place a significant strain on your equipment, so it’s important that you cover your basic needs and prepare for every eventuality.</p>
        <p>Cook yourself a homemade meal with good ingredients and lock the door to the room you rent with the money from your nepo-baby remote consultancy gig. Close out the other applications on your computer with a reflexive manic twitch, recalling for a moment the old dance of your adolescent fingers as they alt-tabbed away at every errant footstep up the stairs. Feel the vulgar flush of chemical manhood course through your body as your mind wanders to what you’re about to do.</p>
        <p>Look at the requirements for what you’re trying to accomplish. Even if your hardware is no limitation, there might be obscure first steps and installation packages that need to be worked through. There might be fundamental incompatibilities, conflicts, graphical inconsistencies. You’ll learn early on that if you want your enemies to lock you in chastity belts when you lose, you’ll have to give up on the nice wide hips you want to make in BodySlide. You’ll learn that the mod for kinky furniture won’t work with the ones that revamp the dungeons, or that werewolf cocks are a separate install, or that it’s very, very complex and difficult to modify the base anatomy of your character.</p>
        <p>But for most of these things, there’s a workaround. When in doubt, ask the forums. Watch a YouTube video. Marvel at what’s possible on such old, familiar software. You’ve been playing this game since you were 14, barely beginning to wear your nascent manhood like an oversized jacket. Is it really possible to make <i>Skyrim</i> look like that?</p>
        <p>It is, say the older, more experienced modders. Men, you assume; only men get ill like this, ill enough to run tubes of liquid coolant through a six-thousand-dollar gaming rig just for a few extra lumens of sheen on the latex of their avatar’s ass.</p>
        <p>The sick men stage screenshots of their characters and post them as albums on the forums as monuments to their technical proficiency and lecherous directorial visions. Stare at them as you wait for your treacle-slow internet to finish downloading a 2-gigabyte .zip folder containing the Special Edition version of the Devious Devices bondage packs.</p>
        <p>Imagine how the cold iron cuffs encircling those slender wrists would feel around your own. Imagine how you’d shiver under the hungry gaze of your bandit captors. Feel a dormant muscle twitch in your broad, fat shoulders as you pantomime a struggle against something that is not there.</p>
        <img class="article-screenshot" src="/images/essay-images/rules-for-pornsick-dovahkiin/nullrfpsd6.png" alt="porn-modded skyrim screenshot">
        <h3>KEEP YOUR WORKSPACE ORGANIZED.</h3>
        <p>It’s so easy to get lost when there’s this much to keep track of. There are dozens and dozens of prerequisites, patches, and dependent files strewn messily across the internet. Nothing’s named what it should be, not after all the tweaks and revisions that go into creating and maintaining programs so perverse and byzantine. It will be up to you to sort it out for yourself.</p>
        <p>Make folders. Make sub-folders within those folders. Group your mods by purpose. Build a section for the ones you need just to run the game, then the old gameplay mods, the weapons and armor and quests you installed years ago after hundreds of hours on the base experience.</p>
        <p>Make a folder for the cosmetics, the mods that shape your avatar into something lithe and fuckable. Fill it with files that give your avatar round, plush breasts and thighs, high-poly face meshes, bright locks of hair and sweat-slick skin.</p>
        <p>Make a folder for the mods that let your enemies in. These mods can’t be found on the Nexus or the safe-for-work Reddit forums; no, they require special steps. Fill your browser with tab after tab of mega.nz download links, running them a few at a time to conserve your limited bandwidth. Your reward for this step will be to fill the monsters around you with violent and terrible hunger, and to give them a thousand means by which to sate it.</p>
        <p>Your foes will no longer settle for cutting you down in battle. They’ll want you alive, kicking, screaming into cloth and steel; they’ll desire you, entrap you, use your battle-broken body and haul you back to their camp in skin-tight rubber and jangling chains.</p>
        <p>Shove this final, shameful category within a maze of subcategories to hide it away, as if a few discreetly-named folders can contain the shame and terror that pulses, radioactive, from your hard drive. Feel a dark, tight knot of anguish as you imagine a friend or a family member finding out the depths you’ve reached to appease your gluttony. Imagine your mother learning about her son’s perversions; picture the look on her baffled, mortified face.</p>
        <p>Nest that feeling inside a cascading column of subcompartments. Close the blinds and draw them tight.</p>
        <img class="article-screenshot" src="/images/essay-images/rules-for-pornsick-dovahkiin/nullrfpsd11.png" alt="porn-modded skyrim screenshot">
        <h3>DON’T NEGLECT THE VISUALS.</h3>
        <p>The sick men from the forums run lighting and texture packs that your scrawny little laptop cannot handle. But this game is 11 years old, as old as you were when your awful, shameful feelings first crawled out from the muck of your childhood psyche. With a few hours of work you can still bring dark, rich life to the world inside the computer. Make the old, familiar landscape lush with new grasses and trees. Watch contentedly as golden god-rays streak through redwood branches in the Reach. Play with the settings in Imaginator until you’ve lit and filtered it all to your liking.</p>
        <p>Once you’re in the game properly, see it as your character would. Stare into the dynamic reflection of your avatar’s wide doe eyes in the shimmering waters outside Riverwood and admire the vibrant, humming life of your fantasy.</p>
        <p>Your avatar is the most important part of all of this. Spare nothing in her creation. Give her care, so much care, and watch her beauty grow like flowers under your gentle hand. Download CBBE and BodySlide; tweak the settings of her new body until her proportions are perfect. Adorn her with soft, dewy texture packs for her smooth, clean skin. Give her long, curly hair with jiggle physics, sharp modern eye makeup, custom idle and combat animations. Download armor revamps that flatter her frame, accentuate her curves, embolden her silhouette.</p>
        <p>Spend the opening moments of your first playthrough staring into your screen like a mirror. She’s extraordinary, isn’t she? There’s almost no trace left of the base game’s impressionistic roughness, not anymore. Now, she looks like the girls from your fantasies, and her body is yours to pilot for as long as you sit bathed in the glow of your screen.</p>
        <p>The world outside – your world – cannot be changed with a few easy sliders. Out here, it is carved in stone, a rigid cavern without forks or exits. The face in your dark laptop screen is aging, fattening, sallowing, its sunken eyes hidden behind a too-thick browbone and its round, unhappy jaw dotted with sickly stubble. Choke back the gnarled root of revulsion forcing its way up your throat just in time for the game to finish loading; watch the dark mirror of your screen give way and become a window to the life of a warrior-woman forged from the dense, wet refuse of your malformed fantasies.</p>
        <p>In here, things are different. <i>Skyrim</i> is soft, forgiving clay, protean and moldable, free and flowing and hyper-real. You can enjoy it, in isolation, in the dark private room you have to yourself. It’s alright to indulge, to imagine. None of this has any bearing on reality.</p>
        <img class="article-screenshot" src="/images/essay-images/rules-for-pornsick-dovahkiin/nullrfpsd12.png" alt="porn-modded skyrim screenshot">
        <h3>TAKE YOUR TIME.</h3>
        <p>You worked hard for this. You downloaded dozens, hundreds of files, spent hours configuring and sorting them. You worked through incompatibilities, trawled obscure forums, rummaged around in the guts of your %appdata% folder until you could breeze through its settings and directories like the streets of your old hometown.</p>
        <p>In a couple of weeks, you’ll grow impatient with the pace of gameplay. <i>Skyrim</i> itself – the base, the original, the topsoil of your adolescence, will grow stale and boring. It’ll be the filler between your daily endorphin shots, the tired scaffolding upon which you’ve built a monument to your own uncontrollable perversion.</p>
        <p>But for now, while things are fresh, play it like you used to. Run through the opening quest with practiced, rote indifference. You might begin to worry; even now, even after all the changes, all the effort to squeeze new blood from the old stone, it will all still feel the same, as bleak and unfinished as it always did.</p>
        <p>But then, the first glimpse of the new adornments. The bandit outside Embershard Mine wears latex gloves under her crude furs. She glares at you with renewed anger as the Sneak eye opens and her red dot fades into vision on your compass. You could swear there was something odd to the way she approached you, as if she were seeing some new possibility of victory in the seconds before drawing her blade.</p>
        <p>You’ll be tempted to throw yourself at her, to give in immediately, to surrender at the first sign that someone in this virtual world might want you. You’ll want to sheathe your weapon, watch her whittle down your health with her crude iron axe, watch the awkward, jerking motion of her model as it captures and conquers yours. </p>
        <p>Hold off. Wait. Stagger her with your shield and run her through as if nothing were different. Clear out the mine just as you would in a normal playthrough. Don’t linger too long on the pillory next to the forge, don’t put the locking cuffs and bodysuits on yourself. If there is one virtue that this ugly process has inculcated in you, it is patience. What you want is so terribly, tantalizingly close, but it will be even sweeter if you wait to earn it.</p>
        <img class="article-screenshot" src="/images/essay-images/rules-for-pornsick-dovahkiin/nullrfpsd4.png" alt="porn-modded skyrim screenshot">
        <h3>BE YOUR CHARACTER.</h3>
        <p>Practice merging minds with your avatar. Watch the rays of warm Tamriel sunlight as they stream through the trees. Listen to the birds. Let the stilted, strange dialogue of Riverwood’s people move you; make up a response in your character’s voice. </p>
        <p>Feel the crackling heat of the Sparks in your palm. Permit yourself a rush of sadistic glee as it lances into your foes. Imagine how it would feel to be experiencing this world for the first time, there in person, rather than running your fingers over the same well-worn keys over and over again. Your character might feel curious, brazen, self-satisfied, or angry; make yourself feel that way, too. </p>
        <p>Try as hard as you can to break through the dull haze of distortion that clouds your emotional world. Let her give you permission to feel. The hero of Skyrim, the Dragonborn, is allowed to experience a kaleidoscope of things that you are not.</p>
        <p>There are other feelings she will experience, too. Once you have played enough to truly inhabit her, begin to let those sensations in. Nobody can see you, in your dark room with the blinds drawn. The only person who will punish you for this is yourself. </p>
        <p>Know her terror as the bandit onslaught begins to break through her defenses. Ape her furious defiance as her wounded, broken body is locked in chains, as the first of them mounts her to claim her as his prize. Succumb to their torture; let it alter your mind until you welcome the submission they force upon you, quietly reveling in humiliation as you stagger out of the dungeon in tight, revealing bondage.</p>
        <p>There is so much they will do to you. Reap the fruits of your labor, the hundreds of crashes and hours of downloading. You have filled your avatar’s life with the pure, sickening nectar of violence, and you waited till the perfect moment to harvest it. Enjoy it; God, enjoy it. It is a chemical rush unlike any you have ever felt, and it is all yours. The world is a miasma of rubber and steel, latex and leather, grunts of pain and gag-muffled groans of ecstasy. Let it light you up like a Christmas tree for hours on end. For all your effort, all your patience, it’s what you deserve.</p>
        <img class="article-screenshot" src="/images/essay-images/rules-for-pornsick-dovahkiin/nullrfpsd1.png" alt="porn-modded skyrim screenshot">
        <h3>DO NOT REFLECT ON YOUR ACTIONS FOR EVEN ONE SECOND UNTIL YOU ARE DONE.</h3>
        <p>Later on, lying restless in your bed, you may reflect on the reality of who you are: a man, or something far, far too like one, simulating the violation of women, touching themself again and again to a sick tableau of misogynist brutalization.</p>
        <p>That knowledge is anathema. It is poison. It is the crash after the high, the price exacted by your pleasure. It will destroy your ability to feel anything – any desire at all – without suppressing the urge to retch.</p>
        <p>Make yourself sick with shame. Delete your entire save file, every mod on your computer, the mod manager itself. Uninstall <i>Skyrim</i> and hide its link in your Steam library. </p>
        <p>Purge yourself of it. Disinhabit the woman you made for yourself. Disavow the wretched desire to puppet her perfect body into fates worse than death. See how long you can go without masturbating. It isn’t long. Two weeks later, build it all again.</p>
        <img class="article-screenshot" src="/images/essay-images/rules-for-pornsick-dovahkiin/nullrfpsd5.png" alt="porn-modded skyrim screenshot">
        <h3>DON’T GIVE IN.</h3>
        <p>You can do this as many times as you want. You can do it forever. You will have uninstalled and reinstalled so many times that assembling the game barely registers as toil. This isn’t healthy, of course; you were never under that delusion. It’s an obligation, a duty, like working out or getting blood drawn or pretending you like having your cock sucked when a real woman deigns to give herself to you. It’s not pleasant, even when it’s pleasurable. It’s penance. It’s what people like you have to do. It’s what you fucking deserve.</p>
        <img class="article-screenshot" src="/images/essay-images/rules-for-pornsick-dovahkiin/nullrfpsd8.png" alt="porn-modded skyrim screenshot">
        <p>Bear your life until you can bear it no longer, you stupid wretch. See how long you can go without retreating into your horrible little rape fantasies. God, you make me sick.</p>
        <img class="article-screenshot" src="/images/essay-images/rules-for-pornsick-dovahkiin/nullrfpsd13.png" alt="porn-modded skyrim screenshot">
        <p>You’re never going to get to be the woman in your video game. Nobody will ever touch you like that. Your sad, unhealthy body will never be enough for anyone, not like hers is. Here, alone in your room, covered in the viscous mess of your own depravity, is the best impression of someone worth wanting you’ll ever, ever do. Fuck you.</p>
        <img class="article-screenshot" src="/images/essay-images/rules-for-pornsick-dovahkiin/nullrfpsd7.png" alt="porn-modded skyrim screenshot">
        <p>Keep doing it. Keep doing it. Make yourself sick. Do it again. Do it until something breaks inside, then do the only thing you can. </p>
        <img class="article-screenshot" src="/images/essay-images/rules-for-pornsick-dovahkiin/nullrfpsd9.png" alt="porn-modded skyrim screenshot">
        <h3>…</h3>
        <p>Open your laptop to write. The sun is shining through the window of your bright, cozy room. Someone who loves you is lying asleep in your bed, her chest rising and falling beneath a warm blanket. Brush the long hair from your eyes and ponder, as you do sometimes, whether to revisit the old game, the mods, with their byzantine installations and their bright colors and their strange, sublimated perversions. But it’s such effort for so early in the morning, and there is work to be done among your people, the living and the real. </p>
        <p>Make pancakes with cinnamon and orange zest for when she awakes. Kiss her smiling face.</p>
        <br>
    </div>
</div>