<svelte:head>
	<title>respect the grinch 2</title>
    <meta name="respect the grinch 2 by constance" content="TODO" />
    <meta property="og:title" content="respect the grinch 2">
    <meta property="og:description" content="i don’t even know what to say to you. your dad is fucked up, dude. i’m fucked up, dude.">
    <meta property="og:image" content="https://null.skin/images/essay-images/respect-the-grinch-2/rtg2000.png">
</svelte:head>
<div class="row border-head">
    <div class="article article-body">
        <p></p>
        <div class="title" style="padding-top:0.75rem;">respect the grinch 2</div>
        <div class="row author" style="margin-top:-0.8rem;">
			<a class="nav-item nav-link variable-manrope" href="/creators/constance">
				by constance p.
			</a>
		</div>
        <div class="row article-date">
            December 25, 2025
        </div>
        <img class="article-screenshot" src="/images/essay-images/respect-the-grinch-2/rtg212.png" alt="incomprehensible mess of white lines on black. baby grinch is there, kind of. you can see the ihop logo buried under all of it. hot air balloon. a bisected face.">
        <p>There's a guy on reddit, and his dad is fucking weird.</p>
        <p>fathers are so often afforded eccentricities, but this particular guy liked jim carrey's the grinch enough to write a sequel, with full certainty that if he just presents the pitch and script to the right people, production can begin and his vision could be realised.</p>
        <p>i'm not even sure i can call this eccentricity. i don't know what words can be applied to this man.</p>
        <p>the reddit OP said it reads like the unabomber manifesto, a clear jest to elicit the reader into imagining unhinged scrawlings of an ideal vision of the world, a true slate of reality that must be achieved but also includes prosthetic makeupped jim carrey eating glass. the OP also says his dad gets too drunk every christmas and bemoans his lack of respect given, how his script could've kicked something to gear, made something real happen. that his vision could never be realised if the people most dear to him kept seeing him as an unhinged joker.</p>
        <p>this is. very strange behavior. he's reprimanded, surely, but i think he's ultimately given grace; He's an old man, set in his ways, just stubborn and never letting go of that glint of the world as it should be from his eye. he's done a lot, raised a family, held a house—you have to make peace with the fact that he's a little kooky.</p>
        <p>jim carrey's the grinch is something i can't imagine wanting to watch again, but this man has clearly watched it through several times.</p>
        <p>perhaps every christmas? i can only grasp this habit from an observation that people tend to do these kinds of things with movies. this is typical human behavior. that is as far as my comprehension with this experience goes.</p>
        <p>when i was nineteen or something, my former friend (who i'm certain if he has his way will become a weird dad whose nearest and dearest strive to tolerate) was enthusiastic about celebrating christ mas. he was whooping on it, telling me about how the season will be jolly or some shit, and i felt a strange apprehension creep onto me. it's like the same grimace that's spread onto me from his passion for going on a trip to vancouver, this sort of "this Thing that i've planned will be amazing because i will see the look on these people's faces and they will smile because of what i have caused". this is the only framework through which christmas is real, to me.</p>
        <img class="article-screenshot" src="/images/essay-images/respect-the-grinch-2/rtg2001.png" alt="jim carrey's the grinch with a surprised expression, rendered as white lines on black">
        <p>jim carrey's the grinch gets huge pussy. massive labia spread on behalf of one absolute whoville freak. her entire character revolves around wanting to vacuum clean his bean. she practically gushes like a geyser as she moans the grinch's name in regular conversation and he hasn't said a single word to her. this is canon to the film. this is the only characterisation of her that i remember.</p>
        <p>also all the whos like, have snouts. prosthetic makeup on every single cast member (except for the ones that have to be fuckable—this includes the child).</p>
        <p>all this is before the cat in the hat unearthed burial graves and ate human flesh, before seuss' mangled wife could fend off that fucked up era of hollywood, when directors set their sights on entertaining swaths of families in theaters every christmas using the viscera of those unspoken for.</p>
        <p>people talk about bargain bins, but never the people who buy those dvds and watch them over and over to the point of breaking.</p>
        <p>well, they do, but only as personal anecdotes. like yeah i watched the pagemaster a full dozen times and i have no good explanation as to why. it's just a thing that happens to disposable nothings. sometimes they embed themselves into your life; i only know from second hand how certain pieces of burnt media can just permanently become parts of your life, despite quality, despite permanence, despite vision, even despite any semblence of entertainment value.</p>
        <p>if someone sees themselves in something, they start to believe in it.</p>
        <p>this redditor's dad watched the grinch in his no-pussy-zone cave arguing with his own echoes every christmas, witnessed the grinch grow several inches, observed the unpleasant man become something that could finally feel included in a family. and i'm imagining here that he's repeating this every christmas.</p>
        <p>you can only read bob’s script on some bizarre corpo website that keeps up a paywall for downloading, so i’m only reading it online. if it dies, it dies.</p>
        <img class="article-screenshot" src="/images/essay-images/respect-the-grinch-2/rtg202.png" alt="a children's open storybook. left page: 'grinch 2: the way i see it'. a drawing of the grinch smiling snyly. a stick figure man in the bottom right corner with the text 'by uncle bob'. right page: random drawings of cartoon characters and a house. rendered as white lines on black">
        <p>Uncle Bob's Grinch 2 picks up right where jim carrey's grinch leaves, with a glorious wedding ceremony, including the entirety of whoville, all whooping and cheering to the new family's formation. they fucking love the grinch. everyone is so incredibly happy. the grinch has been slotted in to his rightful place.</p>
        <p>him and uhh martha? martha's her name right? they go on romantic candle lit dinner dates.</p>
        <p>but grinko still needs to be whipped into a human shape: he argues with the waiter, complains the food isn't rotten, tries to eat the wine glass before martha (who also chugged like half a glass of wine just to get through this ordeal of a man she's committed to loving) teaches him something that changes his life:</p>
        <p>the sweet succor of alcohol.</p>
        <p>he swigs the wine, and it changes his demeanour to gentle curiosity, like an orangutan at an astrolabe. his vile tendencies recede, his shit encrusted fur practically peels back to comfortably fit the suit he's placed into. everything works, and enkidubidoo is domesticated in the wink of an eye.</p>
        <p>Sit the fuck down. it's the morning after and he knows what to do. he has a vision so clear that nobody can deny it, and they don't.</p>
        <p> he's gonna take all of the garbage out of mount krumpus or whatever the fuck it was called. he'll sort out what he likes from it, but the entire trash heap mountain is going to be unrecognizable quite soon. he's renovating absolutely everything. ski lift. hotel. sleds. luxury, amenities, gondolas up and down the hill, in and out the cave, who-tax dollars at play, jobs created, econony fulfilled in flushing the slobbing sheds left behind in that absent spot where no man can call home.</p>
        <p>marijuartha loves it. the dastardly fuckold mayor can't object. the contract is signed, the vision is brought to light, he can make his dreams come true.</p>
        <p>work sets out immediately. he yells at his stupid ass dog for being a dogshit construction partner, has his shit fall over a couple times before he quite quickly decides to just hire a contractor (who is paid in potential future profit, since grench has no fucking money). uncle bob pats himself on the back, no longer needing to write the logistics of construction. some guy will do it off-screen, for free. trust me bro, it’ll be successful in the long run. everybody forgets to pay him.</p>
        <img class="article-screenshot" src="/images/essay-images/respect-the-grinch-2/rtg203.png" alt="a children's open storybook. left page: 'grinch 2: the way i see it'. a drawing of the grinch smiling snyly. a stick figure man in the bottom right corner with the text 'by uncle bob'. right page: random drawings of cartoon characters and a house. rendered as white lines on black">
        <p>well, what happens next, bob? we have to put in complete detail how thoroughly well and swimmingly this whole resort is put together, you can't just skip over that. the narrator in this script is performing heavy lifting here. he's doing the visuals for you. everyone loves the gench. his mountain resort is working perfectly and the last traces of the old grinch are gone for good.</p>
        <p>okay yeah yeah alright okay we did the whole resort and hotel ski lift thing, success is heartily achieved.</p>
        <p>everyone loves the gench. but failcuck mayor is steaming. he's a pathetic man who wants nothing more than to fuck gent's wife, would rather take all credit and leave gimminy to rot as a pile of fur and bones. so he concocts a devilish plan. he spreads false rumors, fiendish tall tales of a grinch ethnostate from which this fat fuck miracle man originated from: where his true blood family lies, and has always been held.</p>
        <p>the rumours are circulated, and the image of grinchrael reaches its intended target. grunchatiser believes the tales completely. his own family? his flesh and blood kin, out there waiting for him? it's all a whopilled man could dream of. it’s his buried past, his future, his beautiful horizon, his newfound values becoming realised. he is completely certain of this news as fact, and thus the mayor’s gambit pays off.</p>
        <p>the story then goes into meticulous detail about the grinch’s process of creating, designing, testing and preparing a hot air balloon for travelling southwards.</p>
        <p>of course he doesn’t design or build it himself this time, he contracts a guy named gus, who contracts some professor stated to be basically the same guy as some simpsons professor scientist character. fuck if i know, that’s just the extent of bob’s imagination. people just keep getting contracted, without any real pay.</p>
        <p>Either way it’s a dangerous journey; the winds are wild, quick to change and deadly to those unprepared. but there’s no doubt in gonorrhea’s mind. he’s ready to come see the land of grilk and whoney.</p>
        <p>at first, martha chooses to stay behind, but after some opaque monologue that included some waxing about the grinch’s birthright, she does her best to convince him to let her come with (she says some real weird shit here and it is not clear what she means). who is he to refuse?</p>
        <p>the mayor, so enthused to fuck and suck to cuck the grunc, has his plan backfire completely. he watches the two float away from whoville, its residents anxiously watching the newly betrothed cross into who doesn’t know where.</p>
        <img class="article-screenshot" src="/images/essay-images/respect-the-grinch-2/rtg204.png" alt="screenshot of text: 'thumbs up 97%, 658k views, 91 pages. Grinch 2. Bob C's the Grinch 2. Full Credit to Bob c. Full description. Uploaded byJorbiedot' rendered as white lines on black">
        <p>i really have to mention how thorough this “script” is in showing the chain of events. at least for now.</p>
        <p>gringo didn’t just Get the hot air balloon, we have to see every involved step of the process, from the construction, the practice involved with learning its controls, the fucking test flight where nothing goes wrong. there’s no consideration imparted for a theoretical audience who would watch this movie, or any inkling of an idea on what designing a narrative is actually for. it’s a sequential order of events to explain the next one, being guided by whatever comes to this isolated old man, with zero temperance or clear direction.</p>
        <p>this is bob’s little statuette he whittles away at, something that draws him away from everyone else, an isolating activity in which he dreams of things he’s seen, things he imagines feeling. it’s the kind of writing you get from fan fiction that nobody reads.</p>
        <p>the redditor stated that this script is incomprehensible, unreadable and incoherent. while i somewhat disagree, i do think it’s hard to impart clear meaning from words that splash across walls and create echoes like this: they blend together, and as tones are added, the more a reverberating bassline creeps in, and the less the letters form words, the more the work becomes saturated.</p>
        <p>it gets worse, by the way. like we’re probably 2/5ths of the way through this script because i somehow have this much to say about grinch 2, and the decline hasn’t made itself obvious yet.</p>
        <p>we’re on the top part of the hill in this vehicle, that part on the sledding hill where we’re accelerating at a steady pace, but the flat part ahead of you is visibly shrinking, the tilt starts yawning, and consciously you can piece together that from where you are, you cannot ascertain when or how you will reach peak velocity.</p>
        <p>but the work will pay off, right?</p>
        <p>when this script is finished, his family will finally see the vision.</p>
        <p>when the film is constructed, and it surely will be, the dream will take flight and all will respect his word on the way he sees things. was this what drove him to complete the work?</p>
        <p>gimp and martin crest upon the winds, they look down and see the promised land, and as expected, it all turned out true. the meadow-basin within is crusted with a circle of mountains, of which hundreds of holes are bored, leading to caves upon tunnels where countless green-furred grampkin live. those within the meadow turn their gaze skywards to see the hot air balloon tilting in, getting ready to land without any prior warning.</p>
        <img class="article-screenshot" src="/images/essay-images/respect-the-grinch-2/rtg205.png" alt=" rendered as white lines on black">
        <p>it’s a hubbub.</p>
        <p>they huddle around the landing, forming great green thickets of crowds, fascinated by the outsider grinchkin and his snouted bride. he makes an announcement to all: he’s here to visit his birth family, to correct the mistake his stork made all those years ago, to witness his true birthland.</p>
        <p>gasps abound. they are clearly not taking a friendly attitude towards these outsiders: but from the audience emerges a couple. their names are Frank and Susan, and they warmly welcome the outsiders to stay in their mountainside cave-home.</p>
        <p>and so, over i think the third or fourth dinner table so far, the four start to piece together the mystery of the grongler’s heritage, and i need to set this plot aside because i need to communicate how much of this script consists of eating food. it’s where the main crux of social interaction takes place, where the author’s experiences interfacing with other people really shines. not to be all “the teacher sleeps at school in their own classroom”, but i can’t help but feel like this man’s entire social life is a string of dinners and holidays, those get-togethers that old adults of a certain culture plan where they all gather to drink and eat a housewife’s cooking. where jokes are told and repeated as long as there’s laughter to be had, where humans create a positive feedback loop of interaction, food, drink, merriment and bonding.</p>
        <p>in contexts like these, a joke is a way to close the distance between one another. a successful bit, and laughing at one, is how you demonstrate you are on the same page as the rest of the group. a joke doesn’t actually have to be structurally sound to make one laugh, it’s just so you can share a positive feeling amongst oneself in a shared space.</p>
        <p>i was once orbiting an extended family get-together in my flying saucer as some old guy kept telling the same story over and over and over, hitting the same punchline. as the night went on and it became clear nobody had anything to connect over, they would repeat that punchline, a way to keep the space cohesive, to keep the shared feeling positive and joyful. i think it was about a guy shitting his pants? he was milked for everything he was worth.</p>
        <p>every joke in this script is exactly that kind of joke. the humorless kind that is only told to draw a family closer, one that divorced of context is practically meaningless. and to these jokes, Everyone laughs, every time. instead of tunafish they all chant whoooonafish, they all play pretend, they turn sentences and sentiments into playful jabs to demonstrate understanding of boundaries and preferences. it’s all primate pack bonding. wouldn’t it be silly if this? oh, you and your characteristic. dogs sneezing mid scrabbling to communicate their state of play to one another. laughing open-mouthed with teeth bared to indicate satisfaction with conduct and company, even if behind these cheeks are thoughts like “can we move on?”</p>
        <p>what if there’s nothing to move onto? what if we have to hold on to this poop-pants man because there’s nothing else in our shared life we can agree to laugh about?</p>
        <p>the grinch destroyed your toilet. it’s very stinky.</p>
        <img class="article-screenshot" src="/images/essay-images/respect-the-grinch-2/rtg206.png" alt=" rendered as white lines on black">
        <p>okay alright hold on before i keep expounding i have to keep you updated on the plot. trust me it’s starting to matter less and less.</p>
        <p>the four realise the whole misplaced baby situation topic thing might be connected to hans, a guy living in grinchrael who grew up looking nothing like the others; no green, no hair, only a snout of similarity. mr. hands was supposed to be in whoville, and grimbley in grinchrael (…should i be referring to it by its actual name? because i didnt care to remember it). so they go to the residence of hands’ mother and father, eugene and jean.</p>
        <p>this script loves to make jokes about characters mishearing things. it’s the who’s on first bit, forever. eugene is the butt of that joke, repeatedly. but through that charade it’s finally brought together:</p>
        <p>eugene and jean are the grinch’s parents. and the grinch’s blood name is Ethan.</p>
        <p>the grinch is ethan. his name is ethan greeninch.</p>
        <p>Fucking… ethan stole christmas.</p>
        <p>he is sparsely referred to as the grinch from here on out. it only occurred to me just now that i can’t riff on grangled’s name anymore, i have to call him ethan.</p>
        <p>hello jj abrams it’s time to make a sequel to jim carrey’s the grinch. he’s ethan and we’re ready for filming. his name is ethan and he’s bouncing off the fucking walls about it. he’s in absolute ecstasy to be fitting into this cave-dirt family so well.</p>
        <p>i have to imagine this hole in the wall is a fucking mobile trailer home, now. i can’t get that out of my mind. grinchrael is a trailer park. it explains everything. that’s why it’s fucking like that.</p>
        <p style="padding-top:2rem;">Grinch: "Please, let's take a walk down, I'm way too nervous to just sit around all day, plus I just want to go down and check out the balloon. Make sure nobody has messed with it.”</p>
        <p style="padding-bottom:3rem;">Frank: "I have to say, that's one thing with this village, as cranky as these people are, nobody would touch anything on your balloon. Everyone totally respects other people's property; it's always been that way.”</p>
        <p>this is the sequel to the grinch stole christmas. this is where we’re at. Ethan Respects Private Property. Jim Carrey Family Values. we’re still going. i’m pretty sure bob starts drinking while writing.</p>
        <p style="padding-top:3rem;">Frank: "Anybody ready for some wine?"</p>
        <p>Susan: "Don't you think it's a little early?"</p>
        <p>Martha: "NOPE"</p>
        <p>Grinch: "NOPE"</p>
        <p>Frank: "NOPE"</p>
        <p style="padding-bottom:2rem;">Susan: "Okay, I'm in”</p>
        <p>that sled hill simile i made a while back? we’re returning to that for just a second.</p>
        <p>there’s a certain lurch in downwards momentum that, when applied just right, localises entirely in my grundle. this is that part of the hill. it’s like the world is pulling you down now. it cannot be swayed. it is taking you down with it. apparently my center of mass in these physics equations is directly on the taint, because it bears all of the gravity. the worst ex i’ve ever had (that former friend of mine) would do this on hills in his car and it is the closest we ever had to any kind of genital stimulation, it was through fucking car ramp proxy. just an anecdote i felt like sharing. we’re getting fucking crunked. do i delete this paragraph? HO HO HO.</p>
        <p>grinch and frank look out the window to see if hans is coming.</p>
        <p>Oh, shit, sorry. ethan and frank walk to the window. and ethan just fucking slaps frank in the back of the head. outright bare palm to skull impact.</p>
        <p style="padding-top:2rem;">Susan: "I don't know about you guys but I'm not even hungry"</p>
        <p>Martha: "Me neither"</p>
        <p>Grinch: "Any leftover ham? A ham sandwich might hit the spot for me"</p>
        <p>Frank: "Why don't we just have some of Martha's Whofish salad (Everyone yells out Whonafish) Sorry, Whooooonaaaafish and some snacks or something"</p>
        <p>Martha: "Sounds like a good idea"</p>
        <p>Grinch: "Oh great"</p>
        <p>Martha: "Come on, give it another try"</p>
        <p>Grinch: "What I meant was, oh what a great idea"</p>
        <p>Grinch gets up to take a peek out the front window, walks behind Frank and slaps him in the back of the head</p>
        <p>Frank chuckling says: "What did I do?"</p>
        <p style="padding-bottom:2rem;">Grinch: "I'm sorry, did my hand accidently hit your head?”</p>
        <p>reading this made me feel like an irate video game reviewer going into a meltdown. he just fucking slaps him in the head and ohoh now thats a funny joke, whats going on with ya? Oh well now the salad is done and we’re moving on No no NO hold on the mirth levels are at a serious high. what the FUCK! i included the whole ruminating on food bit in this quote to really communicate what reading this is like now. we’re seriously falling apart. is this the ideal family? is this a bonding gesture? he goes to peek in the window, but just slaps frank in the fucking head, this man he never knew until like yesterday, this day-old stranger turns to this outsider with a smirk like Heho now what’s this whole business about? does bob even know what the fuck he’s writing? is the author even fully cognizant of what is on this page? this sequence of events puts me at a loss for words, which is why i have to pump out my whole fucking chest and fill this paragraph with words. do you see why this drives me so? does it make sense why i’d deign write this whole thing in the first place? nobody can produce something like this on purpose. this sort of artifact cannot be invoked. it just Emerges. and i can’t just say “ethan slaps frank in the head and it’s treated like a joke” and have it sound like anything without this much context. like, what, is that some kind of sitcom bit? drank and thosh? what’s the big deal? and shit maybe on some level you still do feel that way! but like yeah no in fairness you’re probably nodding your head this whole time, like “yeah, uhuh, it’s funny, and this is certainly fertile grounds for your dance to run amuck”. and yeah, sure it is! but i cannot fucking stress how simple i am keeping this! this isn’t just punching mockery, this is fucking insanity! this is a crack in the mold! <span style="font-weight: 600">THIS IS A SHADOW CAST IN THE SILHOUETTE OF SOMETHING EVERYONE CHOOSES TO IGNORE</span></p>
        <p>Here is one type of divinity (setting aside my distaste for divinity itself, i’m only using this as an expression and i feel i must clarify so): One can run through the same grooves in a set path of one’s own design, eroding it into the perfect shape, tracing lines that conform to your very grip. you can recant the same chords, the same steps taken, the same walls that reverberate your focus, and you can create something to your very own design. like a shape whittled to perfection, guided by the grip of your focus as much as your mind, pure intentionality can be made manifest.</p>
        <p>this is not what produced bob ethan grinch 2. this is not that divinity.</p>
        <p>Here is another type of divinity (on a personal level, i might be antitheist—i hold no reign over other’s lives, so i naturally do not even dream of dictating their values, but the idea of god to me is less than useless): Erosion can buffet anything into sleek, worn or sheer surfaces. the same winds given time can puncture holes through rock that whistle day and night, enchanting beholden ears. humans can be eroded, too, and in fact we have been eroded from the very moment of conception. we are built to fit into each other; our fingers interlockable, our nose crooked against chin, our arms around waists and digits on handles. our methods of love and pain have molded us into animals that identify and liken whistling, our first ever curiosities burgeon into the winds that puncture, the room for a potted plant to grow, the obstacles that force our stalk to bend and balk.</p>
        <p>there is no truth to a bonsai.</p>
        <div class="line"></div>
        <p>the script absolutely falls apart from here. it questions its own need to exist by the end, and struggles to decide what is worth telling. it’s not as sharp of a decline as this article: it’s just a petering out, a thinning of substance until the script literally calls out to bob to make it done. yes, the characters make it back to whoville and babies are birthed and the mayor is countercucked or whatever. but it’s all dried up, now. i can’t guess how bob feels about the script beyond this point. maybe he’s just pissed at his family on the principle of their caring, their level of unwilling to entertain his ideas, and that’s the real problem at hand. we can only form the silhouette of what is in his life.</p>
        <p>OH, Fuck, i haven’t even yet addressed the possibility that the reddit OP might read this. dude i just went on a full actual unabomber rant about your dad. i don’t even know what to say to you. your dad is fucked up, dude. i’m fucked up, dude.</p>
        <p>earlier i hinted at a sort of tendency from the cultures i’ve been exposed to give old folk a break, to let the man be stuck in his ways, to let a vehicle keep coasting against the guard rails we’ve installed for sleeping at the wheel. they draw these people closer, gather and huddle despite differences overshadowing the barest of connections one may have had in the past, like bristles huddling for warmth. is this what must be done?</p>
        <img class="article-screenshot" src="/images/essay-images/respect-the-grinch-2/rtg207.png" alt=" rendered as white lines on black">
        <p>OP, i think i hate people like your dad. there is a comfort in knowing that if the day of drying up comes and all you have left of your life is rotten recitation of your core values, you’ll still be invited back, still be included, still be kept warm. is it insane for me to reject this? i could never accept mediocrity like this.</p>
        <p>i’m just the freak side eyeing a family table outside a red robin’s. junior’s drowning chicken nuggets and the father in the window turns white man red at my glare. little ethan’s going to look up and know he’ll become like me. that’s why he’s crying. dad pointing and yelling like i’m his favorite brain damaged handegg star, and i’m licking my teeth both ways before crossing this stalk. nothing can save you from this fate, giblet. from first spurt to last hurt, you either play a sainte, or you lie a grunch. i’m not the kind of person who can save you from this and i think you know there’s no end to it.</p>
        <p>ethan is divorced from truth. his dreams are constricted to the whims of his home, a lie that can only be proven false in another sphere not worth living in. won’t someone shine a light onto this small, shivering creature? the warmth he’s bestowed upon isn’t his. if he were to understand this, truly grisp its consequences, he wouldn’t be part of a happy family. it would be too late for him.</p>
        <p>there is no intervention from my side. how could there be?</p>
        <p>someone in my apartment building has been smoking some pretty loud stuff. it wafts through the floors, which i learned wasn’t isolated to my own living space, but to others as well, because i got an email from the lords of the land. now, tonight, the smell of cover-up incense drifts through, with greater staying power than the herb could’ve achieved. with the cool air drifting through my window, i’m taken back to the shitty little washingtonian highway town i grew up in. i remember my big brother doing the same thing.</p>
        <p>there is nothing that i can say.</p>
        <p>i cannot explain this. the grief cannot be conveyed. i cannot speak because to demonstrate the shape of my guts would be forming sausage links out of them. connections cannot be made.</p>
        <p>there is glass between ethan and i. there is glass between me and you. the form you see is more unreal than you could guess. there are untold ravines of distance and hurt that mean you will never understand.</p>
        <p>i can’t speak this language, because language is communal, and in me there is no community to be formed.</p>
        <p>this howling is only singing. i was never really here with you to begin with.</p>
        <p>you can’t even see past the clown paint, can you?</p>
        <p>fuck you.</p>
        <div style="padding-top:27rem;"></div>
        <div class="line"></div>
        <p>okay, no, i’m sorry (kind of). i shouldn’t just split and dip like this, should i? or, you don’t want me to.</p>
        <p>let’s go out together, you and i. let’s get something to eat.</p>
        <p>let’s go to IHOP.</p>
        <div class="line"></div>
        <div style="padding-top:27rem;"></div>
        <p>when i was a young boy and still living in my dickass highway town whose shiningly defining trait was a large pile of dirt later grafted into the form of a walmart, i was taken out from class by my parents to go tour a new house we would soon move into, located in tgirl israel—seattle.</p>
        <p>on that day, we (on my half-baked dissociated whim) went to IHOP. and i need you to understand the degree to which this establishment was fucking Plastered with illumination studios’ 3D animated grinch movie. every single surface visible was covered in him. it was knee surgery top-to-bottom, front-to-back. special grinch-themed sugar-pasted ass platters, posters lining the walls, green decorations surrounding everything.. i can’t emphasise enough how inundated the place was.</p>
        <p>and i guess IHOP is a place for very small children, too? i mean, fucking clearly. gunch was in their bunch. or, more accurately, in the lunch of the parents who defined their every single minute exposure to culture. and clintsh is an easy sell for that party. you already know what to expect from him: he’s never going to really matter. he is the fart gumt. he will print you a gorillion dollars, guaranteed.</p>
        <p>order whatever you want on the menu, i really do not care. as for myself, i’m just going to get whatever baked flour will appease my neverending gut bacteria circus. they tend to sit the fuck down for things this dense. fuckers never stop acting up.</p>
        <p>surrounded by the minge, i received a clickity sack from my flip-phone. it is a text from my only friend, one (amongst others) i will leave behind forever. it reads</p>
        <p style="text-align:left; margin-left:9vw; margin-top:3rem; margin-bottom:3rem;"><span style="border:1px solid white; padding:1rem;">Dude where are you</span></p>
        <p>i blink, and then look around myself. i take in my surroundings and pointedly ignore the mascot dancing on the grave of an artist i’ve never cared for. and i tell the truth. i respond</p>
        <p style="text-align:right; margin-right:9vw; margin-top:3rem; margin-bottom:3rem;"><span style="border:1px solid white; padding:1rem;">IHOP</span></p>
        <p>i then close my phone. i have reported true, and my word has been spoken. i do not even mention the dreamworks smile forced on the krumpit cunt. i do not check my phone again.</p>
        <p>from my only friend’s perspective, i vanish inbetween classes at school without a trace. he visits my house and nobody’s there. the only response he receives on my whereabouts is that i am at pancake land, and i go completely radio silent for four days straight.</p>
        <p>i made you very aware of this glass keeping me apart from you, yes? i don’t think i need to explain what that does to a person. i’m sure if i painted you a full picture, you’d see a shape and silhouette quite comprehensible.</p>
        <p>i’d have to form sausage links. who gives a shit? who cares?</p>
        <img class="article-screenshot" src="/images/essay-images/respect-the-grinch-2/rtg208.png" alt=" rendered as white lines on black">
        <p>one quite late night when i was younger my big brother took me out to walk to a denny’s so he could expound virtues and wisdoms of life that he earned through his experiences. he talked down to me, a lowly autist who never experienced anything outside his bedroom door. he bestowed his wisdom for life, made me yell at the top of my lungs into the night air, telling me it felt good to even while my eyes were stinging from it. he smoked weed, and at his command we stared at the sky lacking stars, then he quoted pink floyd lyrics like a dick. by his instructions i was stripped to a rhetorical vessel for his expectations and philosophies. he shrouded every conversation into metaphor and picked and poked at me for simply existing as i am.</p>
        <p>denny’s and ihop are both shit, right? i think i remember my old christmas-grinning car-grundling friend filling my rhetorical vessel self with ideals, one of which being the very cheap en-masse calories one can afford at a denny’s. just load up on a shit ton of pancakes one after the other or something like that. i had very little to say about all that; the less i spoke the better.</p>
        <p>did you order what you wanted, here? in this ihop, i mean. that we are in. you and i. the you that is here. did i tell you i was going to tame my stomach with those carbs? my brother refused to let me want nothing, so he ordered a hot chocolate on my stead to the waitress he knew. he chided me for pretending to be grown up, because i was warming my hands on the mug. called me defensive in response. can i really even ask you questions? i don’t think i can get a response. do i just mold what you’re thinking to yourself? what you think of me? do i build an effigy of myself for your own growth?</p>
        <p>i think i was like six years old or something when big brother would shut me up with <span style="font-weight: 600">“Who cares?”</span> or whatever other variations. that still echoes. when i say it, when my voice sounds like my brother’s, i’m sometimes responded to with I care. and i (he) never really have a response to that. caring was never the point.</p>
        <p>do you mind if i refer to this “you” as ethan? don’t worry about it. it clearly only has bearing on myself.</p>
        <p>you’re not going to be satisfied with this meal. if you ordered a meal. rhetorical carbohydrates aren’t going to build up to anything. i can’t give you what you want. you can’t give me what i want. if the point of this trip to ihop with ethan was to connect, this whole bit was doomed from the start. it’s just not feasible.</p>
        <img class="article-screenshot" src="/images/essay-images/respect-the-grinch-2/pickle01.gif" alt=" rendered as white lines on black">
        <p>…no. i have to account for the possibility that you could be chewing into good cooking. if i don’t consider a reality where ethan is satisfied and wants more from me, i’m just not being smart. ethan could be in love with me.</p>
        <p>that does nothing for me.</p>
        <p>I’m The Fucking Grinch, Too. okay? it was me the whole time. i’ll peel my face off or perhaps unclasp a hatch and reveal knotted green fur with pomeranian-style crusty shit eyes. my heart hasn’t budged a fucking inch and i am absolutely flaccid about it.</p>
        <p>this whole article before we came here was written for nullwave. it was accepted, but later denied. i didn’t put enough of myself in it. my menstrual blood wasn’t mixed in the soda fountain. i honestly no longer give a shit about anything i scatted for bob’s sonata. i was too silly, too cynical, too guarded—these are my own words. i didn’t want to take a single step closer to you because nobody should see the trash heap inside krumpitt. i decided for you, before you could even blink, that you wouldn’t smell the cum pit.</p>
        <p>i fucking hate christmas. and i’ve never been impressed by your holiday cheers. your gifts that you use to bare your souls, your group hugs and poetry to soothe your aching minds. at best, it passes through me like piss off the cliff. it was never my domain.</p>
        <p>i’m pretty sure jim carrey grinch made presents as a child in school and they were laughed at or regarded as weird and shitty, and that like, made him isolate himself and shit. martha 100% fetishised him and wanted to smuckle everything that had his whogrease left over, even as a child, so really the grounds for allegory are ripe. fuck it all.</p>
        <img class="article-screenshot" src="/images/essay-images/respect-the-grinch-2/pickle02.gif" alt=" rendered as white lines on black">
        <p>the only way for the grinch to move on is to integrate himself back into whociety. to be like who is to become ethan. swapped like goo. speak no heathen. i gave you the green inch, and i was stopped and asked for the wean mile. is this pornographic to you?</p>
        <p>the whos were always ready to accept a kind grinch. they’re ready to accept a placid grinch, even appreciate him. kids are cruel, wack. the bugs crawling through the fur can be washed off, but they’ve laid eggs and will always come back. you’ll dance with me by the fire, and the only one keeping me away in the dark is myself.</p>
        <p>it’s not deliberate. it’s no accident, either. there is no way to formulate why i don’t dance. i don’t dislike you. i don’t even have the spite necessary to hate this. to assign blame is to be decimated into meal.</p>
        <p>you can imagine any ending you want for the grinch. he could become ethan. he could die bitter. he could calcify, wisen up, move to some other phase of denial or accept his role and erode beyond what emotion can convey. he could run away forever.</p>
        <p>the fury’s gone and done. but my place has never changed. one day, the clown paint materialised on my face, and washing it off has been an exercise in dishonesty and futility.</p>
        <p>i flipped my shit when this wasn’t published. my brain did a practiced backflip the likes i haven’t seen in almost a decade. my psychoclit got tweaked so hard i was ralphing up dust and slapping the floor like an ape. completely swamped with indistinguishable and inutterable tapioca i kept all to myself. i was pimped full of grinch serum.</p>
        <img class="article-screenshot" src="/images/essay-images/respect-the-grinch-2/pickle03.gif" alt=" rendered as white lines on black">
        <p>i can’t stand the sound of my own voice, dude. i understand you love me but i don’t let myself approach anything like this. a dent has been kicked into me in the same spot countless times and it will not be undone. i don’t even know if i can forgive myself for creating an ethan here and pulling you into this whole dialogue to begin with.</p>
        <p>is this milk wholesome and good-for-the-bones? whatever. i’m just the broth, brother.</p>
        <p>is it better this article was smothered for a bit, is there benefit that this section gurgled out in froth? i don’t know, but i am compelled to “finish” this work. completing my bob-ditty was already like pulling teeth. when the spotlight turns to me, and the only lens worth focusing is my self, i can’t bring myself to do it.</p>
        <p>have i grown in face of this adversity, having taken ethan out to ihop? that’s not a yes or no question. that is the only answer i will give.</p>
        <p>should this be published? whatever. you love me. you read this whole thing. i keep asking permission to drop the mike.</p>
        <p>is all i can express how little i express? have i truly shunned the momthtern star? it rips the skin to answer. gramping it wholigan style can’t satisfy me. gin the swipple won’t become farmers. meat discovers neat for nourishment whoney cannot provide. fuck me and nothing comes. my round violet nose-noggin will slosh and wash. i want to be done. i want the gornographicians to nod their head and let me skip the rake.</p>
        <img class="article-screenshot" src="/images/essay-images/respect-the-grinch-2/pickle04.gif" alt=" rendered as white lines on black">
        <p>is this progress? press my gros and turnt no apple. i’m fuckin outta here</p>
        <div class="line"></div>
        <div style="padding-top:180rem;"></div>
        <p>truly, i would wish to be held. you know i’ll leave you behind, no? it will all come fart oo late.</p>
        <p></p>
        <p></p>
    </div>
</div>